// Code generated by protoc-gen-zig
///! package actor_message
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;
/// import package misc
const misc = @import("misc.pb.zig");
/// import package broker
const broker = @import("broker.pb.zig");
/// import package orderbook
const orderbook = @import("orderbook.pb.zig");
/// import package server
const server = @import("server.pb.zig");
/// import package ohlc
const ohlc = @import("ohlc.pb.zig");

pub const OrderbookActor = struct {
    message: ?message_union,

    pub const _message_case = enum {
        start,
        update,
    };
    pub const message_union = union(_message_case) {
        start: orderbook.OrderbookStartRequest,
        update: orderbook.OrderbookUpdate,
        pub const _union_desc = .{
            .start = fd(1, .{ .SubMessage = {} }),
            .update = fd(2, .{ .SubMessage = {} }),
        };
    };

    pub const _desc_table = .{
        .message = fd(null, .{ .OneOf = message_union }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BrokerActor = struct {
    message: ?message_union,

    pub const _message_case = enum {
        init,
        subscribe,
    };
    pub const message_union = union(_message_case) {
        init: broker.BrokerInitRequest,
        subscribe: broker.BrokerSubscribeRequest,
        pub const _union_desc = .{
            .init = fd(1, .{ .SubMessage = {} }),
            .subscribe = fd(2, .{ .SubMessage = {} }),
        };
    };

    pub const _desc_table = .{
        .message = fd(null, .{ .OneOf = message_union }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const OHLCActor = struct {
    message: ?message_union,

    pub const _message_case = enum {
        start,
        update,
    };
    pub const message_union = union(_message_case) {
        start: ohlc.OHLCStartRequest,
        update: ohlc.OHLCUpdate,
        pub const _union_desc = .{
            .start = fd(1, .{ .SubMessage = {} }),
            .update = fd(2, .{ .SubMessage = {} }),
        };
    };

    pub const _desc_table = .{
        .message = fd(null, .{ .OneOf = message_union }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ServerActor = struct {
    message: ?message_union,

    pub const _message_case = enum {
        init,
        accept,
    };
    pub const message_union = union(_message_case) {
        init: server.InitMessage,
        accept: misc.Empty,
        pub const _union_desc = .{
            .init = fd(1, .{ .SubMessage = {} }),
            .accept = fd(2, .{ .SubMessage = {} }),
        };
    };

    pub const _desc_table = .{
        .message = fd(null, .{ .OneOf = message_union }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ConnectionActor = struct {
    message: ?message_union,

    pub const _message_case = enum {
        orderbook_update,
        ohlc_update,
    };
    pub const message_union = union(_message_case) {
        orderbook_update: orderbook.Orderbook,
        ohlc_update: ohlc.OHLCList,
        pub const _union_desc = .{
            .orderbook_update = fd(1, .{ .SubMessage = {} }),
            .ohlc_update = fd(2, .{ .SubMessage = {} }),
        };
    };

    pub const _desc_table = .{
        .message = fd(null, .{ .OneOf = message_union }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
