// Code generated by protoc-gen-zig
///! package broker
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;

pub const BrokerType = enum(i32) {
    KRAKEN = 1,
    _,
};

pub const MarketData = enum(i32) {
    ORDERBOOK = 1,
    OHLC = 2,
    _,
};

pub const BrokerInitRequest = struct {
    broker: BrokerType,

    pub const _desc_table = .{
        .broker = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BrokerSubscribeRequest = struct {
    ticker: ManagedString,
    market_data: MarketData,

    pub const _desc_table = .{
        .ticker = fd(1, .String),
        .market_data = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
