// Code generated by protoc-gen-zig
///! package connection
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;

pub const SubscriptionType = enum(i32) {
    ORDERBOOK = 1,
    OHLC = 2,
    _,
};

pub const SubscribeRequest = struct {
    ticker: ManagedString,
    subscription_type: SubscriptionType,

    pub const _desc_table = .{
        .ticker = fd(1, .String),
        .subscription_type = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const UnsubscribeRequest = struct {
    ticker: ManagedString,
    subscription_type: SubscriptionType,

    pub const _desc_table = .{
        .ticker = fd(1, .String),
        .subscription_type = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
