// Code generated by protoc-gen-zig
///! package ohlc
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;

pub const OHLCList = struct {
    ohlc: ArrayList(OHLC),

    pub const _desc_table = .{
        .ohlc = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const OHLC = struct {
    symbol: ManagedString,
    open: f64,
    high: f64,
    low: f64,
    close: f64,

    pub const _desc_table = .{
        .symbol = fd(1, .String),
        .open = fd(2, .{ .FixedInt = .I64 }),
        .high = fd(3, .{ .FixedInt = .I64 }),
        .low = fd(4, .{ .FixedInt = .I64 }),
        .close = fd(5, .{ .FixedInt = .I64 }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
