// Code generated by protoc-gen-zig
///! package orderbook
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;

pub const Level = struct {
    price: f64,
    quantity: f64,

    pub const _desc_table = .{
        .price = fd(1, .{ .FixedInt = .I64 }),
        .quantity = fd(2, .{ .FixedInt = .I64 }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const Orderbook = struct {
    bids: ArrayList(Level),
    asks: ArrayList(Level),
    max_depth: u32,
    exchange: ManagedString,
    ticker: ManagedString,

    pub const _desc_table = .{
        .bids = fd(1, .{ .List = .{ .SubMessage = {} } }),
        .asks = fd(2, .{ .List = .{ .SubMessage = {} } }),
        .max_depth = fd(3, .{ .Varint = .Simple }),
        .exchange = fd(4, .String),
        .ticker = fd(5, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
