// Code generated by protoc-gen-zig
///! package server
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;

pub const InitMessage = struct {
    host: ManagedString,
    port: u32,
    max_connections: u32,

    pub const _desc_table = .{
        .host = fd(1, .String),
        .port = fd(2, .{ .Varint = .Simple }),
        .max_connections = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
