// Code generated by protoc-gen-zig
///! package ws_message
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
const ManagedStruct = protobuf.ManagedStruct;
/// import package orderbook
const orderbook = @import("orderbook.pb.zig");
/// import package connection
const connection = @import("connection.pb.zig");
/// import package ohlc
const ohlc = @import("ohlc.pb.zig");

pub const ServerMessage = struct {
    message: ?message_union,

    pub const _message_case = enum {
        orderbook,
        ohlc,
    };
    pub const message_union = union(_message_case) {
        orderbook: orderbook.Orderbook,
        ohlc: ohlc.OHLCList,
        pub const _union_desc = .{
            .orderbook = fd(1, .{ .SubMessage = {} }),
            .ohlc = fd(2, .{ .SubMessage = {} }),
        };
    };

    pub const _desc_table = .{
        .message = fd(null, .{ .OneOf = message_union }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ClientMessage = struct {
    message: ?message_union,

    pub const _message_case = enum {
        subscribe,
        unsubscribe,
    };
    pub const message_union = union(_message_case) {
        subscribe: connection.SubscribeRequest,
        unsubscribe: connection.UnsubscribeRequest,
        pub const _union_desc = .{
            .subscribe = fd(1, .{ .SubMessage = {} }),
            .unsubscribe = fd(2, .{ .SubMessage = {} }),
        };
    };

    pub const _desc_table = .{
        .message = fd(null, .{ .OneOf = message_union }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
