syntax = "proto2";

package ohlc;

import "broker.proto";

message OHLCList {
    required string ticker = 1;
    repeated OHLC ohlc = 2;
}

message OHLC {
    required string ticker = 1;
    required double open = 2;
    required double high = 3;
    required double low = 4;
    required double close = 5;
    required uint64 trades = 6;
    required double volume = 7;
    required uint64 interval = 8;
    required string timestamp = 9;
    required uint64 timestamp_unix = 10;
}


message OHLCUpdate {
    required string ticker = 1;
    required double open = 2;
    required double high = 3;
    required double low = 4;
    required double close = 5;
    required uint64 trades = 6;
    required double volume = 7;
    required uint64 interval = 8;
    required string timestamp = 9;
}