syntax = "proto2";

package ohlc;

import "broker.proto";

message OHLCList {
    repeated OHLC ohlc = 1;
}

message OHLC {
    required string symbol = 1;
    required double open = 2;
    required double high = 3;
    required double low = 4;
    required double close = 5;
    required uint64 trades = 6;
    required double volume = 7;
    required uint64 interval = 8;
    required string timestamp = 9;
}

message OHLCInitRequest {
    required broker.BrokerType broker = 1;
}

message OHLCStartRequest {
    required string ticker = 1;
}

message OHLCUpdate {
    required string symbol = 1;
    required double open = 2;
    required double high = 3;
    required double low = 4;
    required double close = 5;
    required uint64 trades = 6;
    required double volume = 7;
    required uint64 interval = 8;
    required string timestamp = 9;
}