syntax = "proto2";

package orderbook;

import "broker.proto";


message OrderbookInitRequest {
    required broker.BrokerType broker = 1;
}

message OrderbookStartRequest {
    required string ticker = 1;
}

message OrderbookLevel {
    required double price = 1;
    required double size = 2;
}

message OrderbookUpdate {
    required string symbol = 1;
    repeated OrderbookLevel bids = 2;
    repeated OrderbookLevel asks = 3;
    required uint64 checksum = 4;
    optional string timestamp = 5;
}